name: Build AppImage and publish to registry

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  id-token: write
  contents: read

jobs:
  appimage:
    name: AppImage Build Intel RealSense
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: buildjet-8vcpu-ubuntu-2204-arm
            container:
              image: ghcr.io/viam-modules/viam-camera-realsense:arm64
              options: --platform linux/arm64
            make_target: appimage-arm64
            platform: linux/arm64
          - os: ubuntu-latest
            container:
              image: ghcr.io/viam-modules/viam-camera-realsense:amd64
              options: --platform linux/amd64
            make_target: appimage-amd64
            platform: linux/amd64

    container: ${{ matrix.container }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make ${{ matrix.make_target }} TAG_VERSION="${{ github.ref_name }}"

      - name: bundle module
        run: |
          cp packaging/appimages/deploy/viam-camera-realsense-*.AppImage viam-camera-realsense.AppImage
          tar czf module.tar.gz viam-camera-realsense.AppImage

      - uses: viamrobotics/upload-module@main
        with:
          platform: ${{ matrix.platform }}
          version: ${{ github.ref_name }}
          key-id: ${{ secrets.viam_key_id }}
          key-value: ${{ secrets.viam_key_value }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKFLOW_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Upload Files
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          headers: "cache-control: no-cache"
          path: 'packaging/appimages/deploy/'
          destination: 'packages.viam.com/apps/camera-servers/'
          glob: '*'
          parent: false
          gzip: false
