name: Build AppImage Intel RealSense

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  appimage:
    name: AppImage Build Intel RealSense
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          - os: 'buildjet-8vcpu-ubuntu-2204-arm'
            container:
              image: ghcr.io/viam-modules/viam-camera-realsense:arm64
              options: '--platform linux/arm64'
            make_target: appimage-arm64
          - os: 'ubuntu-latest'
            container:
              image: ghcr.io/viam-modules/viam-camera-realsense:amd64
              options: '--platform linux/amd64'
            make_target: appimage-amd64

    container: ${{ matrix.container }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: make ${{ matrix.make_target }}

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GCP_WORKFLOW_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Upload Files
        uses: google-github-actions/upload-cloud-storage@v0.10.4
        with:
          headers: "cache-control: no-cache"
          path: 'packaging/appimages/deploy/'
          destination: 'packages.viam.com/apps/camera-servers/'
          glob: '*'
          parent: false
          gzip: false
